# Generated for the LIFE submission manager starter.
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Addition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("applies_to_all_active", models.BooleanField(default=True, help_text="施設で算定中の場合、原則として全利用者を対象候補にするか。")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=80)),
                ("service_type", models.CharField(choices=[("day_care", "通所介護"), ("specific_facility", "特定施設入居者生活介護"), ("nursing_home", "介護老人福祉施設"), ("geriatric_health", "介護老人保健施設"), ("medical_care", "介護医療院"), ("home_rehab", "訪問リハビリテーション"), ("day_rehab", "通所リハビリテーション"), ("other", "その他")], max_length=40)),
                ("facility_number", models.CharField(blank=True, max_length=30)),
                ("active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facilities", to="core.organization")),
            ],
            options={"ordering": ["organization__name", "name"]},
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=80)),
                ("display_name", models.CharField(help_text="実名ではなく施設内管理番号や仮名での運用を推奨します。", max_length=120)),
                ("service_start_date", models.DateField()),
                ("service_end_date", models.DateField(blank=True, null=True)),
                ("life_registered", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clients", to="core.facility")),
            ],
            options={"ordering": ["display_name"]},
        ),
        migrations.CreateModel(
            name="FacilityAddition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("addition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_additions", to="core.addition")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facility_additions", to="core.facility")),
            ],
            options={"ordering": ["facility", "addition__name", "-start_date"]},
        ),
        migrations.CreateModel(
            name="ClientAddition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("anchor_date", models.DateField(blank=True, help_text="ADL維持等加算の評価対象利用開始月など、ルール計算の基準日。", null=True)),
                ("eligible", models.BooleanField(default=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="client_additions", to="core.client")),
                ("facility_addition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="client_assignments", to="core.facilityaddition")),
            ],
        ),
        migrations.CreateModel(
            name="ClientEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(choices=[("hospital_admission", "入院"), ("hospital_discharge", "退院"), ("service_restart", "利用再開"), ("service_end", "利用終了"), ("plan_created", "個別機能訓練計画作成"), ("plan_updated", "個別機能訓練計画変更"), ("other", "その他")], max_length=40)),
                ("event_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="core.client")),
            ],
            options={"ordering": ["client", "event_date", "id"]},
        ),
        migrations.CreateModel(
            name="RuleVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=40)),
                ("rule_kind", models.CharField(choices=[("scientific_care", "科学的介護"), ("individual_function", "個別機能訓練"), ("adl_maintenance", "ADL維持等"), ("generic_interval", "汎用定期提出")], max_length=40)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("interval_months", models.PositiveSmallIntegerField(default=3)),
                ("due_month_offset", models.PositiveSmallIntegerField(default=1)),
                ("due_day", models.PositiveSmallIntegerField(default=10)),
                ("service_types", models.JSONField(blank=True, default=list, help_text="空配列は全サービス種別。例: [\"day_care\", \"specific_facility\"]")),
                ("config", models.JSONField(blank=True, default=dict)),
                ("source_title", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=800)),
                ("source_published_on", models.DateField()),
                ("change_summary", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("addition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rule_versions", to="core.addition")),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_life_rules", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["addition__name", "-effective_from"]},
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("admin", "法人管理者"), ("manager", "施設管理者"), ("editor", "入力担当"), ("viewer", "閲覧のみ")], default="viewer", max_length=20)),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="core.facility")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facility_memberships", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_month", models.DateField(help_text="評価・提出対象月の月初日")),
                ("evaluation_date", models.DateField()),
                ("due_date", models.DateField()),
                ("submission_kind", models.CharField(choices=[("initial", "初回提出"), ("periodic", "定期提出"), ("end", "終了時提出"), ("plan_created", "計画作成時"), ("plan_updated", "計画変更時"), ("adl_initial", "ADL初月"), ("adl_six_month", "ADL6月目"), ("manual_review", "要確認")], max_length=30)),
                ("status", models.CharField(choices=[("pending", "未提出"), ("due_soon", "期限接近"), ("overdue", "期限超過"), ("submitted", "提出済み"), ("not_required", "対象外"), ("review", "要確認")], default="pending", max_length=20)),
                ("reason", models.CharField(max_length=500)),
                ("generated", models.BooleanField(default=True)),
                ("computed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("addition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="submission_schedules", to="core.addition")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submission_schedules", to="core.client")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submission_schedules", to="core.facility")),
                ("rule_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="submission_schedules", to="core.ruleversion")),
            ],
            options={"ordering": ["due_date", "facility", "client__display_name"]},
        ),
        migrations.CreateModel(
            name="SubmissionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(choices=[("manual", "手動登録"), ("csv", "CSV取込"), ("system", "システム連携")], default="manual", max_length=30)),
                ("accepted", models.BooleanField(default=True)),
                ("external_reference", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("schedule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="records", to="core.submissionschedule")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="life_submission_records", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="LifeRegistrationSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField()),
                ("registered_count", models.PositiveIntegerField()),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="life_snapshots", to="core.facility")),
            ],
            options={"ordering": ["-snapshot_date"]},
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("severity", models.CharField(choices=[("info", "情報"), ("warning", "警告"), ("error", "エラー")], max_length=20)),
                ("message", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="validation_issues", to="core.client")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="validation_issues", to="core.facility")),
            ],
            options={"ordering": ["resolved", "-severity", "-created_at"]},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=80)),
                ("object_type", models.CharField(blank=True, max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=80)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("facility", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="core.facility")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="facility", constraint=models.UniqueConstraint(fields=("organization", "code"), name="unique_facility_code_per_org")),
        migrations.AddConstraint(model_name="client", constraint=models.UniqueConstraint(fields=("facility", "external_id"), name="unique_client_external_id")),
        migrations.AddConstraint(model_name="facilityaddition", constraint=models.UniqueConstraint(fields=("facility", "addition", "start_date"), name="unique_facility_addition_start")),
        migrations.AddConstraint(model_name="clientaddition", constraint=models.UniqueConstraint(fields=("client", "facility_addition", "start_date"), name="unique_client_addition_start")),
        migrations.AddConstraint(model_name="ruleversion", constraint=models.UniqueConstraint(fields=("addition", "version"), name="unique_rule_version")),
        migrations.AddConstraint(model_name="membership", constraint=models.UniqueConstraint(fields=("user", "facility"), name="unique_user_facility_membership")),
        migrations.AddConstraint(model_name="submissionschedule", constraint=models.UniqueConstraint(fields=("client", "addition", "target_month", "submission_kind"), name="unique_submission_schedule")),
        migrations.AddConstraint(model_name="liferegistrationsnapshot", constraint=models.UniqueConstraint(fields=("facility", "snapshot_date"), name="unique_life_snapshot_date")),
        migrations.AddIndex(model_name="validationissue", index=models.Index(fields=["facility", "resolved", "severity"], name="issue_facility_status_idx")),
    ]
